---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covenant
  namespace: covenant
spec:
  selector:
    matchLabels:
      app: covenant
  replicas: 1
  template:
    metadata:
      labels:
        app: covenant
    spec:
      containers:
      - name: covenant
        image: archbungle/kovenant:0.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: ADMIN_PASSWORD
          value: "randomstuff"
        - name: ADMIN_USER
          value: "master"
        ports:
          - name: tcp-7443
            containerPort: 7443
          - name: tcp-8080
            containerPort: 8080
          - name: tcp-4443
            containerPort: 4443

---

kind: Service
apiVersion: v1
metadata:
  name: covenant-service
  namespace: covenant
spec:
  type: NodePort
  selector:
    app: covenant
  ports:
    - name: tcp-7443
      port: 7443
      nodePort: 30743
      protocol: TCP
    - name: tcp-8080
      port: 8181
      nodePort: 30818
      protocol: TCP
    - name: tcp-4443
      port: 4443
      nodePort: 30443
      protocol: TCP
